name: Build

on:
  workflow_call:
    inputs:
      attach_to_release:
        description: 'Attach JAR to release'
        required: false
        type: boolean
        default: false
      upload_artifact:
        description: 'Upload JAR as artifact'
        required: false
        type: boolean
        default: false
    secrets:
      token:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs

      - if: ${{ inputs.attach_to_release }}
        name: Upload JAR to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          files: build/libs/burp-vps-proxy.jar
